version: '3'
services:
  echo-server-a:
    image: echo-server
    ports:
      - "8081:8080"
    environment:
      - MESSAGE=Hello from a
    
  echo-server-b:
    image: echo-server
    ports:
      - "8082:8080"
    environment:
      - MESSAGE=Hello from b

  reverse-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
